name: note_app

description: "A Flutter note-taking app with CI/CD pipeline"

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  
  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Database
  shared_preferences: ^2.5.3
  
  
  # Utilities
  intl: ^0.19.0
  http: ^1.1.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.2       # Moved from dev_dependencies
  sqflite: ^2.3.2        # Moved from dev_dependencies  
  path: ^1.9.0           # Moved from dev_dependencies
  intl: ^0.19.0          # Moved from dev_dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  # Linting
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.9
  #sqflite_common_ffi: ^2.3.0
  
  # Code generation
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  # Assets (uncomment and add paths as needed)
  # assets:
  #   - images/
  #   - icons/
  
  # Fonts (uncomment and configure as needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

  flutter_lints: ^5.0.0
  mockito: ^5.4.4        # Add for testing
  build_runner: ^2.4.9 
  sqflite_common_ffi: ^2.3.6  # Add for code generation

flutter:
  uses-material-design: true

